version: "3.8"

services:
  # Database
  mongodb:
    image: mongo:latest
    container_name: bookstore_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  # API
  api:
    build: .
    container_name: bookstore_api
    ports: 
      - "5001:5001"
    env_file:
      - ".env"
    depends_on:
      - mongodb

volumes:
  mongo-data:
